config/routes.rb
Rails.application.routes.draw do
  get 'preferences/edit'
  get 'preferences/update'
  resources :preferences do
    collection do
      patch :sort
    end
  end

  get 'sessions/new'

  get '/home', to: "pages#home"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  root 'sessions#new'
end

app/models/application.rb
class Application < ApplicationRecord
  has_many :preferences, foreign_key: "application_id"
  has_many :users, through: :preferences
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/preference.rb
class Preference < ApplicationRecord
  belongs_to :user
  belongs_to :application
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.name = name.downcase}
  validates :name, presence: true, length: {maximum: 100}, uniqueness: {case_sensitive: false}
  has_many :preferences, foreign_key: "user_id"
  has_many :applications, through: :preferences
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def login
  end
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  def edit
  end
  
  def index
    @preferences=Preference.order(:position)
  end
  
  def update
    @preference=Preference.find(params[:id])
    #debugger
    params[:preference]=params
    @preference.update(preference_params)
    render 'edit'
  end
  
  def sort
    params[:preference].each_with_index do |id, index|
      Preference.where(id: id).update_all(position: index+1)
    end
    
    head :ok
  end
  
  private
    def preference_params
      #debugger
      params.require(:preference).permit(:active)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  
  def create
    user=User.find_by(name: params[:session][:name].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to home_path
    else
      flash.now[:danger]="Invalid Username and Password"
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id]=user.id
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="btn right"><%=link_to 'Add, Remove, and Sort Apps', preferences_edit_path%></div>
<h1 class="center">Home Page</h1>
<div class="apps">
  <% Preference.all.order(:position).each do |p|%>
    <%if p.user_id==current_user.id && p.active%>
      <div class="app_box" style=<%="background-color:#{p.application.color.downcase}"%>>
        <div class="link center"><%=link_to p.application.name, p.application.link%></div>
        <div class="description center"><%=p.application.description%></div>
      </div>
    <%end%>
  <% end %>
</div>

app/views/pages/login.html.erb
<h1>Pages#login</h1>
<p>Find me in app/views/pages/login.html.erb</p>

app/views/preferences/edit.html.erb
<div class="btn right"><%=link_to 'Return to Home', home_path%></div>
<h1 class="center">Preferences</h1>
<div class="list" id="apps" data-url="<%= sort_preferences_path%>">
  <% Preference.all.order(:position).each do |p|%>
    <%if p.user_id==current_user.id%>
      <div class="option" style=<%="background-color:#{p.application.color.downcase}"%> id=<%=dom_id(p)%>>
        <%if p.active%>
            <div class="activation right"><%=link_to 'Deactivate', preferences_update_path(preference: p, id: p.id, active: false) %></div>
        <%else%>
            <div class="activation right"><%=link_to 'Activate', preferences_update_path(preference: p, id: p.id, active: true)%></div>
        <%end%>
        <div class="description center"><%=p.application.description%></div>
        <div class="link center"><%=p.application.name%></div>
      </div>
    <%end%>
  <% end %>
</div>